CourseEnrollmentSystem/Models/DatabaseContext.cs
using CourseEnrollmentSystem.Models.Entities;
using Microsoft.EntityFrameworkCore;


namespace CourseEnrollmentSystem.Models
{
    public class DatabaseContext : DbContext
    {
        public DatabaseContext(DbContextOptions options) : base(options)
        {
        }
        public DbSet<Student> Students { get; set; }
        public DbSet<Enrollment> Enrollments { get; set; }
        public DbSet<Course> Courses { get; set; }
       
    }
}

CourseEnrollmentSystem/Models/Entities/Course.cs
namespace CourseEnrollmentSystem.Models.Entities
{
    public class Course
    {
        public int Id { get; set; }
        public string Title { get; set; } = " ";
        public ICollection<Enrollment>? Enrollments { get; set; }
    }
}

CourseEnrollmentSystem/Models/Entities/Enrollment.cs
namespace CourseEnrollmentSystem.Models.Entities
{
    public class Enrollment
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public Student? Student { get; set; }

        public int CourseId { get; set; }
        public Course? Course { get; set; }
        public DateTime EnrolledOn { get; set; } 
    }
}

CourseEnrollmentSystem/Models/Entities/Student.cs
using CourseEnrollmentSystem.Models.Entities;

namespace CourseEnrollmentSystem.Models.Entities
{
    public class Student
    {
        public int Id { get; set; }
        public string FullName { get; set; } = " ";
        public ICollection<Enrollment>? Enrollments { get; set; }
    }
}

CourseEnrollmentSystem/Models/ErrorViewModel.cs
namespace CourseEnrollmentSystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CourseEnrollmentSystem/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;

namespace CourseEnrollmentSystem.Controllers
{
    public class CourseController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CourseEnrollmentSystem/Controllers/EnrollmentController.cs
using CourseEnrollmentSystem.Models;
using CourseEnrollmentSystem.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace CourseEnrollmentSystem.Controllers
{
    public class EnrollmentController : Controller
    {
        private readonly DatabaseContext _context;
        public EnrollmentController(DatabaseContext context)
        {
            _context = context;
        }
        public IActionResult Enrolled(int studentId)
        {
            ViewBag.StudentId = studentId;
            ViewBag.Courses = _context.Courses.ToList();
            ViewData["Title"] = "Enroll Student";
            return View();
        }
        [HttpPost]
        public IActionResult Enrolled(int studentId, int courseId)
        {
            var enrollment = new Enrollment
            {
                StudentId = studentId,
                CourseId = courseId,
                EnrolledOn = DateTime.Now
            };
            _context.Enrollments.Add(enrollment);
            _context.SaveChanges();

            TempData["Message"] = "Enrollment Successfull!"; 
            return RedirectToAction("Details", "Student");

        }
    }
}

CourseEnrollmentSystem/Controllers/HomeController.cs
using System.Diagnostics;
using CourseEnrollmentSystem.Models;
using Microsoft.AspNetCore.Mvc;

namespace CourseEnrollmentSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CourseEnrollmentSystem/Controllers/StudentController.cs
using CourseEnrollmentSystem.Models;
using CourseEnrollmentSystem.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Scaffolding.Metadata;

namespace CourseEnrollmentSystem.Controllers
{
    public class StudentController : Controller
    {
        private readonly DatabaseContext context;
        public StudentController(DatabaseContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            ViewData["Title"] = "Student List";
            var students = context.Students.ToList();
            return View(students);
        }

        public IActionResult Create()
        {
            ViewBag.PageTitle = "Create Student";
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName")] Student student)
        {
            if (ModelState.IsValid)
            {
                context.Add(student);
                await context.SaveChangesAsync();
                TempData["SuccessMessage"] = "Student Created Successfully!";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "Error!";
            return View(student);
        }

        public IActionResult Details(int id)
        {
            var student = context.Students
                .Include(e => e.Enrollments)
                .ThenInclude(c => c.Course)
                .FirstOrDefault(s => s.Id == id);
            return View(student);
        }
    }
}

CourseEnrollmentSystem/Views/Enrollment/Enrolled.cshtml
<h1>@ViewData[index:"Title"]</h1>
<form asp-action ="Enroll" method="post">
    <input type="hidden" name="studentId" value=" @ViewBag.StudentId"
/>
    <label>Select Course</label>
    <select name=" courseId" class="form-control">
        @foreach(var c in ViewBag.Courses){
            <option value="@c.Id">@c.title</option>
        }
    </select>
    <br />
    <button type="submit" class="btn btn-primary">Enroll</button>
</form>

CourseEnrollmentSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CourseEnrollmentSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CourseEnrollmentSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CourseEnrollmentSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enrollment" asp-action="Enrolled">Enrollment</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CourseEnrollmentSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CourseEnrollmentSystem/Views/Shared/_Notification.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
@if (TempData["SuccessMessage"] != null)
{

    <div class="alert alert-dismissible alert-success">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Success!</strong> @TempData["SuccessMessage"]
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
            toastr.success('@TempData["SuccessMessage"]')
        });
    </script>
}

@if (TempData["error"] != null)
{

    <div class="alert alert-dismissible alert-warning">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <h4 class="alert-heading">Error!</h4>
        <p class="mb-0">@TempData["error"]</p>
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
            toastr.error('@TempData["error"]')
        });
    </script>
}

CourseEnrollmentSystem/Views/Student/Create.cshtml
@model CourseEnrollmentSystem.Models.Entities.Student
@{
    ViewData["Title"] = "Create Student";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CourseEnrollmentSystem/Views/Student/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

CourseEnrollmentSystem/Views/Student/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

CourseEnrollmentSystem/Views/Student/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

CourseEnrollmentSystem/Views/Student/Index.cshtml
@model IEnumerable<CourseEnrollmentSystem.Models.Entities.Student>
<h2>@ViewData[index:"Title"]</h2>
@if(TempData[key: "Success"] != null)
{
    <div class="alert alert-success">@TempData[key:"Success"]</div>
}
<p>
    <a asp-action="Create">Add Student</a>
</p>
<partial name="_Notification" />
<table class="table">
    <tr>
        <th>Name</th>
        <th></th>
    </tr>

    @foreach (var s in Model)
    {
        <tr>
            <td>@s.FullName</td>
            <td>
                <a href="/Student/Details/@s.Id">Details</a>
            </td>
        </tr>
    }
</table>

@* <h1>Index</h1>

<p>
    <a asp-action="Create">Add a new Student</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table> *@